server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5333/jwt_security #sid or servicename
    username: yousef
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # tell hibernate which dialect to use
        format-sql: true
    show-sql: true
  main:
    web-application-type: servlet

  application:
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970